Add needed spacing & update scope name
krokedil/sign-in-with-klarna pull request #10
Opened 2024-12-20 13:07 UTC by anyakro

Add missing space to the scope string and update the scope name for profile:language.

2024-12-20 13:09 UTC, anyakro commented
Is this a sufficient solution, or do I need to consider/update the filter and saved locale data?

2024-12-20 16:07 UTC, MichaelBengtsson requested changes

2024-12-20 16:07 UTC, MichaelBengtsson commented on src/Settings.php
> +			$required = 'openid offline_access customer:login profile:name profile:email profile:phone profile:billing_address ';
When we return this value, we should probably add a trim to remove any trailing whitespace characters incase none of the optional scopes are added, just to not cause an errors when sending this to Klarna.

2025-01-08 13:35 UTC, MichaelBengtsson approved these changes

2025-01-08 13:35 UTC, merged